target_compile_definitions(Widrolo_Engine_3D PRIVATE
        HAPTIC_SDL=${HAPTIC_SDL_VAL}
        HAPTIC_STEAM_INPUT=${HAPTIC_STEAM_INPUT_VAL}
        HAPTIC_XINPUT=${HAPTIC_XINPUT_VAL}
        HAPTIC_PLAYSTATION=${HAPTIC_PLAYSTATION_VAL}
        HAPTIC_NINTENDO=${HAPTIC_NINTENDO_VAL}
        HAPTIC_APPLE=${HAPTIC_APPLE_VAL}
)

target_compile_definitions(Widrolo_Engine_3D PRIVATE HAPTIC_BACKEND=${HAPTIC_SDL_VAL})